name: Build

on: workflow_dispatch
       
jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfltk1.3-dev fluid gettext appstream
          sudo apt-get install -y libgnutls28-dev nettle-dev libgmp-dev
          sudo apt-get install -y libxtst-dev libxdamage-dev libxfixes-dev libxrandr-dev libpam-dev
          sudo apt-get install -y libavcodec-dev libavutil-dev libswscale-dev
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build
      - name: Build
        working-directory: build
        run: make
      - name: Install
        working-directory: build
        run: make tarball
      - uses: actions/upload-artifact@v3
        with:
          name: Linux (Ubuntu)
          path: build/tigervnc-*.tar.gz

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
      - name: Install dependencies
        run: |
          pacman --sync --noconfirm --needed \
            make mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake
          pacman --sync --noconfirm --needed \
            mingw-w64-x86_64-fltk mingw-w64-x86_64-libjpeg-turbo \
            mingw-w64-x86_64-gnutls mingw-w64-x86_64-pixman \
            mingw-w64-x86_64-nettle mingw-w64-x86_64-gmp
      - name: Configure
        run: cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Debug -S . -B build
      - name: Build
        working-directory: build
        run: make
      - name: Install
        working-directory: build
        env:
          MSYS2_PATH_TYPE: inherit
        run: make installer winvnc_installer
      - uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: build/release/tigervnc*.exe
